language: go
go:
  - 1.10.2

sudo: false

env:
  - DEP_VERSION="0.4.1"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - go get github.com/mattn/goveralls

install:
  - dep ensure

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - goveralls -coverprofile=coverage.txt -service=travis-ci
