language: go
go:
  - "1.14.x"

sudo: false

env:
  - GO111MODULE="on"

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -v -race -parallel 4 -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - goveralls -coverprofile=coverage.txt -service=travis-ci -ignore=generate/avro_test_data/*,generate/generate_test_data/*,struct_test_data/*
