= JSON Schema Transform
:toc:
:toc-placement!:

toc::[]

== Transform Object
The transform object in the schema will be used as meta-data, next to the field, in order to instruct the consumers on how to transform data from the existing format, to this new schema. It uses JSONPath to identify the data location.

The transform object has the following properties:
```
"transform": {                                   // top level object
    "cumulo|presentationv4": {                   // this is an arbitrary name, which is an identifier to the consumer that this instructions set is destined for them.
        "from" : [                               // array of transform instruction objects
            {
                "jsonPath": ""                   // jsonPath instructing the consumer where to find the data in the *input stream*.
                "xmlPath": ""                    // xmlPath instructing the consumer where to find the data in the *input stream* via xPath
                "operations": [                  // a list of operations to further execute on the data. The input defined by jsonPath will be passed to the operations
                                {
                                    "type": "x", // type of operation to perform on the data. These are methods to further mutate the data that jsonPath does not currently support
                                    "args": {
                                        ...      // discussed below based on the type of operation.
                                    }
                                }
                            ]
            }
        ],
         "method": "first|last|concatenate",     // the method to be used in the event that there are more than one "from" paths. Can be one of first, last, concatenate
         "methodOptions": {                      // options to be passed along to the chosen method.
             "concatenateDelimiter": ""          // optional delimiter to be used when concatenating multiple jsonPath items. Must be a string
         }
    }                  
}   
```

=== Implementation Requirements

- The jsonPath selector is an identifier of the location of the _input_ path. All paths should start with the root object `$`. The exception here is for an Array of objects, where the relative `@` operator should be used on the leaf objects to signify the location is relative to the parent transform (more on this below)

- The xPath selector is an identifier of the location of the _input_ path. All paths will start with the root object '/'. The exceptions here being for an Array of objects, or an object with a transform. For an array a group of nodes will be selected with '//' and all item paths in the array will be relative to that selection, this will be executed once for each array element. For an object if a transform xPath is declared all fields inside the object will be relative to that selected node.

- If a transform object exists on a property, the consumer should automatically use that. In the event a transform object does not exist on a property, the consumer should attempt to find the value in the input at the location that corresponds to the same location in the schema. In other words, if the consumer is operating on schema field `$.foo.bar` which has no `transform.<consumer>` property, the consumer should use `$.foo.bar` as the location to pull the value from the input. This provides a nice "default" for those fields that are 1:1 match.

- `first` is the default method of transform

- Arrays should have a transform object. The properties of the array should then use the relative `@` jsonPath selector. The consumer will then iterate over the input array and utilize the relative path to find the type specific field at that location in the array

- Objects can optionally have an xmlPath transform. If an object does have this transform all fields inside of it will be relative to that selection with it now acting as the root node, meaning nodes above the selected object transform node will be inaccessible inside that object. If a transform is placed on an object and it is not found all children fields inside the object will be skipped.


=== Operations

Operations allow further mutation of data, for mutation types that are not currently supported by jsonPath.

.Operations
[options="header"]
|===
| Name | Input | Output | Argument Key | Argument Value
| duration | string in the format "MM:SS" or "HH:MM:SS" | integer of seconds | |
| changeCase | string | string | to | lower or upper
| inverse | boolean | boolean | |
| max | array | object | by | A relative JSONPath selector that identifies a number to take the max of, ie `@.encodingRate`
| | | | return | A relative JSONPath selector that identifies the property to return of that item identified as "max", ie `@.url`
| replace | string | string | regex | Regex string that will be used to match the part of the string that will be replaced
| | | | new | The value to replace with, this will be placed at capture group 1
| split | string | array | on | The string to split on
| timeParse | string | string | format | The format to parse the time from
| | | | layout | The layout of the returned date string
| currentTime | string | string | |
| toCamelCase | string | string | delimiter | The delimiter to split the string on
| stringToInteger | string | integer | |
| stringToFloat | string | number | |
|===

