// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
package timespointers

import (
	"github.com/actgardner/gogen-avro/v7/compiler"
	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
	"io"
)

type AppearanceURLs_record struct {
	Original bool `json:"original"`

	Url string `json:"url"`
}

const AppearanceURLs_recordAvroCRC64Fingerprint = "\x9e\xacb⊴\xc7\xda"

func NewAppearanceURLs_record() *AppearanceURLs_record {
	return &AppearanceURLs_record{}
}

func DeserializeAppearanceURLs_record(r io.Reader) (*AppearanceURLs_record, error) {
	t := NewAppearanceURLs_record()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err
	}
	return t, err
}

func DeserializeAppearanceURLs_recordFromSchema(r io.Reader, schema string) (*AppearanceURLs_record, error) {
	t := NewAppearanceURLs_record()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err
	}
	return t, err
}

func writeAppearanceURLs_record(r *AppearanceURLs_record, w io.Writer) error {
	var err error
	err = vm.WriteBool(r.Original, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Url, w)
	if err != nil {
		return err
	}
	return err
}

func (r *AppearanceURLs_record) Serialize(w io.Writer) error {
	return writeAppearanceURLs_record(r, w)
}

func (r *AppearanceURLs_record) Schema() string {
	return "{\"fields\":[{\"default\":false,\"name\":\"original\",\"namespace\":\"factCheckClaims.appearanceURLs\",\"type\":\"boolean\"},{\"name\":\"url\",\"namespace\":\"factCheckClaims.appearanceURLs\",\"type\":\"string\"}],\"name\":\"factCheckClaims.appearanceURLs.appearanceURLs_record\",\"type\":\"record\"}"
}

func (r *AppearanceURLs_record) SchemaName() string {
	return "factCheckClaims.appearanceURLs.appearanceURLs_record"
}

func (_ *AppearanceURLs_record) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ *AppearanceURLs_record) SetInt(v int32)       { panic("Unsupported operation") }
func (_ *AppearanceURLs_record) SetLong(v int64)      { panic("Unsupported operation") }
func (_ *AppearanceURLs_record) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ *AppearanceURLs_record) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ *AppearanceURLs_record) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ *AppearanceURLs_record) SetString(v string)   { panic("Unsupported operation") }
func (_ *AppearanceURLs_record) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *AppearanceURLs_record) Get(i int) types.Field {
	switch i {
	case 0:
		return &types.Boolean{Target: &r.Original}
	case 1:
		return &types.String{Target: &r.Url}
	}
	panic("Unknown field index")
}

func (r *AppearanceURLs_record) SetDefault(i int) {
	switch i {
	case 0:
		r.Original = false
		return
	}
	panic("Unknown field index")
}

func (r *AppearanceURLs_record) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ *AppearanceURLs_record) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *AppearanceURLs_record) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *AppearanceURLs_record) Finalize()                        {}

func (_ *AppearanceURLs_record) AvroCRC64Fingerprint() []byte {
	return []byte(AppearanceURLs_recordAvroCRC64Fingerprint)
}
