package avro_test_data

// Code generated by github.com/GannettDigital/jstransform; DO NOT EDIT.

import "time"

type Complex struct {
	Simple

	Caption string `json:"caption"`
	Credit  string `json:"credit"`
	// The available cropped images
	Crops []struct {
		Height float64 `json:"height"`
		Name   string  `json:"name"`
		// full path to the cropped image file
		Path string `json:"path"`
		// a long
		// multi-line description
		RelativePath string  `json:"relativePath"`
		Width        float64 `json:"width"`
	} `json:"crops"`
	Cutline        string    `json:"cutline,omitempty"`
	DatePhotoTaken time.Time `json:"datePhotoTaken"`
	Orientation    string    `json:"orientation"`
	OriginalSize   struct {
		Height float64 `json:"height"`
		Width  float64 `json:"width"`
	} `json:"originalSize"`
	// a type
	Type string `json:"type"`
	// Universal Resource Locator
	URL struct {
		// The full Canonical URL
		Absolute string `json:"absolute"`
		Meta     struct {
			Description string `json:"description"`
			SiteName    string `json:"siteName"`
		} `json:"meta,omitempty"`
		Publish string `json:"publish"`
	} `json:"URL"`
}
