package avro_test_data

// Code generated by github.com/GannettDigital/jstransform; DO NOT EDIT.

import "time"

type Times struct {
	NonRequiredDate time.Time `json:"nonRequiredDate,omitempty"`
	RequiredDate    time.Time `json:"requiredDate"`
}
