// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.

package arrays

import (
	"github.com/actgardner/gogen-avro/compiler"
	"github.com/actgardner/gogen-avro/container"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
	"io"
)

type Info_record struct {
	Name string
	Age  int64
}

func NewInfo_recordWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := &Info_record{}
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

func DeserializeInfo_record(r io.Reader) (*Info_record, error) {
	t := NewInfo_record()

	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	return t, err
}

func NewInfo_record() *Info_record {
	return &Info_record{}
}

func (r *Info_record) Schema() string {
	return "{\"fields\":[{\"name\":\"name\",\"namespace\":\"parents.info\",\"type\":\"string\"},{\"name\":\"age\",\"namespace\":\"parents.info\",\"type\":\"long\"}],\"name\":\"info_record\",\"namespace\":\"parents.info\",\"type\":\"record\"}"
}

func (r *Info_record) SchemaName() string {
	return "parents.info.info_record"
}

func (r *Info_record) Serialize(w io.Writer) error {
	return writeInfo_record(r, w)
}

func (_ *Info_record) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ *Info_record) SetInt(v int32)       { panic("Unsupported operation") }
func (_ *Info_record) SetLong(v int64)      { panic("Unsupported operation") }
func (_ *Info_record) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ *Info_record) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ *Info_record) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ *Info_record) SetString(v string)   { panic("Unsupported operation") }
func (_ *Info_record) SetUnionElem(v int64) { panic("Unsupported operation") }
func (r *Info_record) Get(i int) types.Field {
	switch i {
	case 0:
		return (*types.String)(&r.Name)
	case 1:
		return (*types.Long)(&r.Age)

	}
	panic("Unknown field index")
}
func (r *Info_record) SetDefault(i int) {
	switch i {

	}
	panic("Unknown field index")
}
func (_ *Info_record) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Info_record) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *Info_record) Finalize()                        {}

type Info_recordReader struct {
	r io.Reader
	p *vm.Program
}

func NewInfo_recordReader(r io.Reader) (*Info_recordReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewInfo_record()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &Info_recordReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r *Info_recordReader) Read() (*Info_record, error) {
	t := NewInfo_record()
	err := vm.Eval(r.r, r.p, t)
	return t, err
}
