// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.

package arrays

import (
	"github.com/actgardner/gogen-avro/vm/types"
	"io"
)

type ByteWriter interface {
	Grow(int)
	WriteByte(byte) error
}

type StringWriter interface {
	WriteString(string) (int, error)
}

func encodeInt(w io.Writer, byteCount int, encoded uint64) error {
	var err error
	var bb []byte
	bw, ok := w.(ByteWriter)
	// To avoid reallocations, grow capacity to the largest possible size
	// for this integer
	if ok {
		bw.Grow(byteCount)
	} else {
		bb = make([]byte, 0, byteCount)
	}

	if encoded == 0 {
		if bw != nil {
			err = bw.WriteByte(0)
			if err != nil {
				return err
			}
		} else {
			bb = append(bb, byte(0))
		}
	} else {
		for encoded > 0 {
			b := byte(encoded & 127)
			encoded = encoded >> 7
			if !(encoded == 0) {
				b |= 128
			}
			if bw != nil {
				err = bw.WriteByte(b)
				if err != nil {
					return err
				}
			} else {
				bb = append(bb, b)
			}
		}
	}
	if bw == nil {
		_, err := w.Write(bb)
		return err
	}
	return nil

}

func writeArrayLong(r []int64, w io.Writer) error {
	err := writeLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeLong(e, w)
		if err != nil {
			return err
		}
	}
	return writeLong(0, w)
}

func writeArrayParents_record(r []*Parents_record, w io.Writer) error {
	err := writeLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeParents_record(e, w)
		if err != nil {
			return err
		}
	}
	return writeLong(0, w)
}

func writeArrayString(r []string, w io.Writer) error {
	err := writeLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeString(e, w)
		if err != nil {
			return err
		}
	}
	return writeLong(0, w)
}

func writeArrays(r *Arrays, w io.Writer) error {
	var err error
	err = writeLong(r.AvroWriteTime, w)
	if err != nil {
		return err
	}
	err = writeBool(r.AvroDeleted, w)
	if err != nil {
		return err
	}
	err = writeArrayLong(r.Heights, w)
	if err != nil {
		return err
	}
	err = writeArrayParents_record(r.Parents, w)
	if err != nil {
		return err
	}

	return nil
}

func writeBool(r bool, w io.Writer) error {
	var b byte
	if r {
		b = byte(1)
	}

	var err error
	if bw, ok := w.(ByteWriter); ok {
		err = bw.WriteByte(b)
	} else {
		bb := make([]byte, 1)
		bb[0] = b
		_, err = w.Write(bb)
	}
	if err != nil {
		return err
	}
	return nil
}

func writeLong(r int64, w io.Writer) error {
	downShift := uint64(63)
	encoded := uint64((r << 1) ^ (r >> downShift))
	const maxByteSize = 10
	return encodeInt(w, maxByteSize, encoded)
}

func writeParents_record(r *Parents_record, w io.Writer) error {
	var err error
	err = writeLong(r.Count, w)
	if err != nil {
		return err
	}
	err = writeArrayString(r.Children, w)
	if err != nil {
		return err
	}

	return nil
}

func writeString(r string, w io.Writer) error {
	err := writeLong(int64(len(r)), w)
	if err != nil {
		return err
	}
	if sw, ok := w.(StringWriter); ok {
		_, err = sw.WriteString(r)
	} else {
		_, err = w.Write([]byte(r))
	}
	return err
}

type ArrayStringWrapper []string

func (_ *ArrayStringWrapper) SetBoolean(v bool)                { panic("Unsupported operation") }
func (_ *ArrayStringWrapper) SetInt(v int32)                   { panic("Unsupported operation") }
func (_ *ArrayStringWrapper) SetLong(v int64)                  { panic("Unsupported operation") }
func (_ *ArrayStringWrapper) SetFloat(v float32)               { panic("Unsupported operation") }
func (_ *ArrayStringWrapper) SetDouble(v float64)              { panic("Unsupported operation") }
func (_ *ArrayStringWrapper) SetBytes(v []byte)                { panic("Unsupported operation") }
func (_ *ArrayStringWrapper) SetString(v string)               { panic("Unsupported operation") }
func (_ *ArrayStringWrapper) SetUnionElem(v int64)             { panic("Unsupported operation") }
func (_ *ArrayStringWrapper) Get(i int) types.Field            { panic("Unsupported operation") }
func (_ *ArrayStringWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *ArrayStringWrapper) Finalize()                        {}
func (_ *ArrayStringWrapper) SetDefault(i int)                 { panic("Unsupported operation") }
func (r *ArrayStringWrapper) AppendArray() types.Field {
	var v string

	*r = append(*r, v)
	return (*types.String)(&(*r)[len(*r)-1])
}

type ArrayParents_recordWrapper []*Parents_record

func (_ *ArrayParents_recordWrapper) SetBoolean(v bool)                { panic("Unsupported operation") }
func (_ *ArrayParents_recordWrapper) SetInt(v int32)                   { panic("Unsupported operation") }
func (_ *ArrayParents_recordWrapper) SetLong(v int64)                  { panic("Unsupported operation") }
func (_ *ArrayParents_recordWrapper) SetFloat(v float32)               { panic("Unsupported operation") }
func (_ *ArrayParents_recordWrapper) SetDouble(v float64)              { panic("Unsupported operation") }
func (_ *ArrayParents_recordWrapper) SetBytes(v []byte)                { panic("Unsupported operation") }
func (_ *ArrayParents_recordWrapper) SetString(v string)               { panic("Unsupported operation") }
func (_ *ArrayParents_recordWrapper) SetUnionElem(v int64)             { panic("Unsupported operation") }
func (_ *ArrayParents_recordWrapper) Get(i int) types.Field            { panic("Unsupported operation") }
func (_ *ArrayParents_recordWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *ArrayParents_recordWrapper) Finalize()                        {}
func (_ *ArrayParents_recordWrapper) SetDefault(i int)                 { panic("Unsupported operation") }
func (r *ArrayParents_recordWrapper) AppendArray() types.Field {
	var v *Parents_record
	v = NewParents_record()

	*r = append(*r, v)
	return (*r)[len(*r)-1]
}

type ArrayLongWrapper []int64

func (_ *ArrayLongWrapper) SetBoolean(v bool)                { panic("Unsupported operation") }
func (_ *ArrayLongWrapper) SetInt(v int32)                   { panic("Unsupported operation") }
func (_ *ArrayLongWrapper) SetLong(v int64)                  { panic("Unsupported operation") }
func (_ *ArrayLongWrapper) SetFloat(v float32)               { panic("Unsupported operation") }
func (_ *ArrayLongWrapper) SetDouble(v float64)              { panic("Unsupported operation") }
func (_ *ArrayLongWrapper) SetBytes(v []byte)                { panic("Unsupported operation") }
func (_ *ArrayLongWrapper) SetString(v string)               { panic("Unsupported operation") }
func (_ *ArrayLongWrapper) SetUnionElem(v int64)             { panic("Unsupported operation") }
func (_ *ArrayLongWrapper) Get(i int) types.Field            { panic("Unsupported operation") }
func (_ *ArrayLongWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *ArrayLongWrapper) Finalize()                        {}
func (_ *ArrayLongWrapper) SetDefault(i int)                 { panic("Unsupported operation") }
func (r *ArrayLongWrapper) AppendArray() types.Field {
	var v int64

	*r = append(*r, v)
	return (*types.Long)(&(*r)[len(*r)-1])
}
