// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.

package repeats

import (
	"github.com/actgardner/gogen-avro/compiler"
	"github.com/actgardner/gogen-avro/container"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
	"io"
)

type Repeats struct {

	// The timestamp when this avro data is written. Useful for identifying the newest row of data sharing keys.
	AvroWriteTime int64

	// This is set to true when the Avro data is recording a delete in the source data.
	AvroDeleted bool
	Height      *UnionNullLong
	SomeDateObj *SomeDateObj_record
	Type        string
	Visible     bool
	Width       *UnionNullDouble
}

func NewRepeatsWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := &Repeats{}
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

func DeserializeRepeats(r io.Reader) (*Repeats, error) {
	t := NewRepeats()

	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	return t, err
}

func NewRepeats() *Repeats {
	return &Repeats{}
}

func (r *Repeats) Schema() string {
	return "{\"fields\":[{\"doc\":\"The timestamp when this avro data is written. Useful for identifying the newest row of data sharing keys.\",\"logicalType\":\"timestamp-millis\",\"name\":\"AvroWriteTime\",\"type\":\"long\"},{\"default\":false,\"doc\":\"This is set to true when the Avro data is recording a delete in the source data.\",\"name\":\"AvroDeleted\",\"type\":\"boolean\"},{\"name\":\"height\",\"type\":[\"null\",\"long\"]},{\"default\":{},\"name\":\"someDateObj\",\"type\":{\"fields\":[{\"name\":\"type\",\"namespace\":\"someDateObj\",\"type\":\"string\"},{\"default\":false,\"name\":\"visible\",\"namespace\":\"someDateObj\",\"type\":\"boolean\"}],\"name\":\"someDateObj_record\",\"namespace\":\"someDateObj\",\"type\":\"record\"}},{\"name\":\"type\",\"type\":\"string\"},{\"default\":false,\"name\":\"visible\",\"type\":\"boolean\"},{\"name\":\"width\",\"type\":[\"null\",\"double\"]}],\"name\":\"Repeats\",\"type\":\"record\"}"
}

func (r *Repeats) SchemaName() string {
	return "Repeats"
}

func (r *Repeats) Serialize(w io.Writer) error {
	return writeRepeats(r, w)
}

func (_ *Repeats) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ *Repeats) SetInt(v int32)       { panic("Unsupported operation") }
func (_ *Repeats) SetLong(v int64)      { panic("Unsupported operation") }
func (_ *Repeats) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ *Repeats) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ *Repeats) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ *Repeats) SetString(v string)   { panic("Unsupported operation") }
func (_ *Repeats) SetUnionElem(v int64) { panic("Unsupported operation") }
func (r *Repeats) Get(i int) types.Field {
	switch i {
	case 0:
		return (*types.Long)(&r.AvroWriteTime)
	case 1:
		return (*types.Boolean)(&r.AvroDeleted)
	case 2:
		r.Height = NewUnionNullLong()
		return r.Height
	case 3:
		r.SomeDateObj = NewSomeDateObj_record()
		return r.SomeDateObj
	case 4:
		return (*types.String)(&r.Type)
	case 5:
		return (*types.Boolean)(&r.Visible)
	case 6:
		r.Width = NewUnionNullDouble()
		return r.Width

	}
	panic("Unknown field index")
}
func (r *Repeats) SetDefault(i int) {
	switch i {
	case 1:
		r.AvroDeleted = false
		return
	case 3:

		return
	case 5:
		r.Visible = false
		return

	}
	panic("Unknown field index")
}
func (_ *Repeats) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Repeats) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *Repeats) Finalize()                        {}

type RepeatsReader struct {
	r io.Reader
	p *vm.Program
}

func NewRepeatsReader(r io.Reader) (*RepeatsReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewRepeats()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &RepeatsReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r *RepeatsReader) Read() (*Repeats, error) {
	t := NewRepeats()
	err := vm.Eval(r.r, r.p, t)
	return t, err
}
