package buildstructs

// This file was autogenerated by https://github.com/GannettDigital/jstransform

type BreakingNews struct {
	Base

	AssociatedAssetId string `json:"associatedAssetId,omitempty"`
	Body              struct {
		Desktop []struct {
			Type  string `json:"type"`
			Value string `json:"value"`
		} `json:"desktop"`
		Mobile []struct {
			Type  string `json:"type"`
			Value string `json:"value"`
		} `json:"mobile"`
	} `json:"body"`
	Developing            bool   `json:"developing"`
	FullText              string `json:"fullText"`
	LayoutPriorityAssetId string `json:"layoutPriorityAssetId"`
	Type                  string `json:"type"`
}
