package buildstructs

// This file was autogenerated by https://github.com/GannettDigital/jstransform

type Gallery struct {
	Base

	PromoImage struct {
		ThumbnailAssetId string `json:"thumbnailAssetId"`
		ThumbnailPath    string `json:"thumbnailPath"`
	} `json:"promoImage"`
	Type string `json:"type"`
}
