package buildstructs

// This file was autogenerated by https://github.com/GannettDigital/jstransform

type OEmbed struct {
	Base

	AssetId         string  `json:"assetId,omitempty"`
	AuthorName      string  `json:"authorName,omitempty"`
	AuthorURL       string  `json:"authorURL,omitempty"`
	CacheAge        float64 `json:"cacheAge"`
	DURI            string  `json:"dURI,omitempty"`
	Description     string  `json:"description,omitempty"`
	Height          float64 `json:"height,omitempty"`
	Html            string  `json:"html,omitempty"`
	Name            string  `json:"name,omitempty"`
	OembedType      string  `json:"oembedType,omitempty"`
	OriginalType    string  `json:"originalType,omitempty"`
	Originkey       string  `json:"originkey,omitempty"`
	ProviderName    string  `json:"providerName"`
	ProviderURL     string  `json:"providerURL,omitempty"`
	ThumbnailHeight float64 `json:"thumbnailHeight,omitempty"`
	ThumbnailURL    string  `json:"thumbnailURL,omitempty"`
	ThumbnailWidth  float64 `json:"thumbnailWidth,omitempty"`
	Type            string  `json:"type,omitempty"`
	URL             string  `json:"URL"`
	Version         string  `json:"version,omitempty"`
	Width           float64 `json:"width,omitempty"`
}
