package buildstructs

// This file was autogenerated by https://github.com/GannettDigital/jstransform

type Text struct {
	Base

	AggregateId string `json:"aggregateId,omitempty"`
	Body        struct {
		Desktop []struct {
			Type  string `json:"type"`
			Value string `json:"value,omitempty"`
		} `json:"desktop"`
		Mobile []struct {
			Type  string `json:"type"`
			Value string `json:"value,omitempty"`
		} `json:"mobile"`
	} `json:"body"`
	CanonicalURL          string `json:"canonicalURL,omitempty"`
	FullText              string `json:"fullText,omitempty"`
	Geolocation           string `json:"geolocation,omitempty"`
	LayoutPriorityAssetId string `json:"layoutPriorityAssetId"`
	Pagetitle             string `json:"pagetitle,omitempty"`
	SeoTitle              string `json:"seoTitle,omitempty"`
	ShortMobileURL        string `json:"shortMobileURL,omitempty"`
	Type                  string `json:"type,omitempty"`
	VersionHash           string `json:"versionHash,omitempty"`
}
