package buildstructs

// This file was autogenerated by https://github.com/GannettDigital/jstransform

type Video struct {
	Base

	BrightcoveAccountId string  `json:"brightcoveAccountId"`
	BrightcoveId        string  `json:"brightcoveId"`
	Credit              string  `json:"credit,omitempty"`
	GannettTracking     string  `json:"gannettTracking,omitempty"`
	HlsURL              string  `json:"hlsURL,omitempty"`
	Length              float64 `json:"length"`
	Mp4URL              string  `json:"mp4URL"`
	Origin              string  `json:"origin"`
	Renditions          []struct {
		AudioOnly    bool    `json:"audioOnly"`
		Codec        string  `json:"codec"`
		Container    string  `json:"container"`
		DisplayName  string  `json:"displayName,omitempty"`
		Duration     float64 `json:"duration"`
		EncodingRate float64 `json:"encodingRate"`
		Height       float64 `json:"height"`
		Size         float64 `json:"size"`
		Type         string  `json:"type"`
		URL          string  `json:"URL"`
		Width        float64 `json:"width"`
	} `json:"renditions,omitempty"`
	Thumbnail  string `json:"thumbnail,omitempty"`
	Type       string `json:"type"`
	VideoStill string `json:"videoStill"`
}
