// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
package simple

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
)

type UnionNullDoubleTypeEnum int

const (
	UnionNullDoubleTypeEnumDouble UnionNullDoubleTypeEnum = 1
)

type UnionNullDouble struct {
	Null      *types.NullVal
	Double    float64
	UnionType UnionNullDoubleTypeEnum
}

func writeUnionNullDouble(r *UnionNullDouble, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullDoubleTypeEnumDouble:
		return vm.WriteDouble(r.Double, w)
	}
	return fmt.Errorf("invalid value for *UnionNullDouble")
}

func NewUnionNullDouble() *UnionNullDouble {
	return &UnionNullDouble{}
}

func (_ *UnionNullDouble) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullDouble) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullDouble) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullDouble) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullDouble) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullDouble) SetString(v string)  { panic("Unsupported operation") }
func (r *UnionNullDouble) SetLong(v int64) {
	r.UnionType = (UnionNullDoubleTypeEnum)(v)
}
func (r *UnionNullDouble) Get(i int) types.Field {
	switch i {
	case 0:
		return r.Null
	case 1:
		return &types.Double{Target: (&r.Double)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullDouble) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionNullDouble) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionNullDouble) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullDouble) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionNullDouble) Finalize()                        {}

func (r *UnionNullDouble) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("null"), nil
	}
	switch r.UnionType {
	case UnionNullDoubleTypeEnumDouble:
		return json.Marshal(map[string]interface{}{"double": r.Double})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullDouble")
}

func (r *UnionNullDouble) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if value, ok := fields["double"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.Double)
	}
	return fmt.Errorf("invalid value for *UnionNullDouble")
}
