package pointers

// Code generated by github.com/GannettDigital/jstransform; DO NOT EDIT.

type Targeted_pointers struct {
	AnotherField string `json:"anotherField,omitempty"`
	// The available cropped images
	Crops []*ComplexCrops `json:"crops,omitempty"`
	// Universal Resource Locator
	URL *ComplexURL `json:"URL,omitempty"`
}
