// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
package complex

import (
	"github.com/actgardner/gogen-avro/v7/compiler"
	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
	"io"
)

type URL_record struct {
	Absolute string `json:"absolute"`

	Meta *UnionNullMeta_record `json:"meta"`

	Publish string `json:"publish"`
}

const URL_recordAvroCRC64Fingerprint = "\x01\xe05\xab[+r6"

func NewURL_record() *URL_record {
	return &URL_record{}
}

func DeserializeURL_record(r io.Reader) (*URL_record, error) {
	t := NewURL_record()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err
	}
	return t, err
}

func DeserializeURL_recordFromSchema(r io.Reader, schema string) (*URL_record, error) {
	t := NewURL_record()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err
	}
	return t, err
}

func writeURL_record(r *URL_record, w io.Writer) error {
	var err error
	err = vm.WriteString(r.Absolute, w)
	if err != nil {
		return err
	}
	err = writeUnionNullMeta_record(r.Meta, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Publish, w)
	if err != nil {
		return err
	}
	return err
}

func (r *URL_record) Serialize(w io.Writer) error {
	return writeURL_record(r, w)
}

func (r *URL_record) Schema() string {
	return "{\"fields\":[{\"name\":\"absolute\",\"namespace\":\"URL\",\"type\":\"string\"},{\"name\":\"meta\",\"namespace\":\"URL\",\"type\":[\"null\",{\"fields\":[{\"name\":\"description\",\"namespace\":\"URL.meta\",\"type\":\"string\"},{\"name\":\"siteName\",\"namespace\":\"URL.meta\",\"type\":\"string\"}],\"name\":\"meta_record\",\"namespace\":\"URL.meta\",\"type\":\"record\"}]},{\"name\":\"publish\",\"namespace\":\"URL\",\"type\":\"string\"}],\"name\":\"URL.URL_record\",\"type\":\"record\"}"
}

func (r *URL_record) SchemaName() string {
	return "URL.URL_record"
}

func (_ *URL_record) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ *URL_record) SetInt(v int32)       { panic("Unsupported operation") }
func (_ *URL_record) SetLong(v int64)      { panic("Unsupported operation") }
func (_ *URL_record) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ *URL_record) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ *URL_record) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ *URL_record) SetString(v string)   { panic("Unsupported operation") }
func (_ *URL_record) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *URL_record) Get(i int) types.Field {
	switch i {
	case 0:
		return &types.String{Target: &r.Absolute}
	case 1:
		r.Meta = NewUnionNullMeta_record()

		return r.Meta
	case 2:
		return &types.String{Target: &r.Publish}
	}
	panic("Unknown field index")
}

func (r *URL_record) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *URL_record) NullField(i int) {
	switch i {
	case 1:
		r.Meta = nil
		return
	}
	panic("Not a nullable field index")
}

func (_ *URL_record) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *URL_record) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *URL_record) Finalize()                        {}

func (_ *URL_record) AvroCRC64Fingerprint() []byte {
	return []byte(URL_recordAvroCRC64Fingerprint)
}
