package test_data

import "time"

// Code generated by github.com/GannettDigital/jstransform; DO NOT EDIT.

type Arrays struct {
	Heights []int64 `json:"heights,omitempty"`
	Parents []struct {
		Count    int64     `json:"count"`
		Children []string  `json:"children"`
		Date     time.Time `json:"date"`
		Info     struct {
			Name string `json:"name"`
			Age  int64  `json:"age"`
		} `json:"info"`
	} `json:"parents"`
}
