package test_data

// Code generated by github.com/GannettDigital/jstransform; DO NOT EDIT.

type Arrays struct {
	Heights []int64 `json:"heights,omitempty"`
	Parents []struct {
		Count    int64    `json:"count"`
		Children []string `json:"children"`
	} `json:"parents"`
}
