package test_data

// Code generated by github.com/GannettDigital/jstransform; DO NOT EDIT.

type Repeats struct {
	Height      int64 `json:"height,omitempty"`
	SomeDateObj struct {
		Type    string `json:"type"`
		Visible bool   `json:"visible,omitempty"`
	} `json:"someDateObj,omitempty"`
	Type    string  `json:"type"`
	Visible bool    `json:"visible,omitempty"`
	Width   float64 `json:"width,omitempty"`
}
