package test

// This file was autogenerated by https://github.com/GannettDigital/jstransform

type Simple struct {
	Type    string  `json:"type"`
	Visible bool    `json:"visible,omitempty"`
	Width   float64 `json:"width,omitempty"`
}
