// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
package complex

import (
	"io"

	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
)

func writeArrayCrops_record(r []*Crops_record, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeCrops_record(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayCrops_recordWrapper struct {
	Target *[]*Crops_record
}

func (_ *ArrayCrops_recordWrapper) SetBoolean(v bool)                { panic("Unsupported operation") }
func (_ *ArrayCrops_recordWrapper) SetInt(v int32)                   { panic("Unsupported operation") }
func (_ *ArrayCrops_recordWrapper) SetLong(v int64)                  { panic("Unsupported operation") }
func (_ *ArrayCrops_recordWrapper) SetFloat(v float32)               { panic("Unsupported operation") }
func (_ *ArrayCrops_recordWrapper) SetDouble(v float64)              { panic("Unsupported operation") }
func (_ *ArrayCrops_recordWrapper) SetBytes(v []byte)                { panic("Unsupported operation") }
func (_ *ArrayCrops_recordWrapper) SetString(v string)               { panic("Unsupported operation") }
func (_ *ArrayCrops_recordWrapper) SetUnionElem(v int64)             { panic("Unsupported operation") }
func (_ *ArrayCrops_recordWrapper) Get(i int) types.Field            { panic("Unsupported operation") }
func (_ *ArrayCrops_recordWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *ArrayCrops_recordWrapper) Finalize()                        {}
func (_ *ArrayCrops_recordWrapper) SetDefault(i int)                 { panic("Unsupported operation") }
func (r *ArrayCrops_recordWrapper) NullField(i int) {
	panic("Unsupported operation")
}

func (r *ArrayCrops_recordWrapper) AppendArray() types.Field {
	var v *Crops_record
	v = NewCrops_record()

	*r.Target = append(*r.Target, v)

	return (*r.Target)[len(*r.Target)-1]
}
