// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.

package complex

import (
	"github.com/actgardner/gogen-avro/compiler"
	"github.com/actgardner/gogen-avro/container"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
	"io"
)

type Crops_record struct {
	Height       float64
	Name         string
	Path         string
	RelativePath string
	Width        float64
}

func NewCrops_recordWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := &Crops_record{}
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

func DeserializeCrops_record(r io.Reader) (*Crops_record, error) {
	t := NewCrops_record()

	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	return t, err
}

func NewCrops_record() *Crops_record {
	return &Crops_record{}
}

func (r *Crops_record) Schema() string {
	return "{\"fields\":[{\"name\":\"height\",\"namespace\":\"crops\",\"type\":\"double\"},{\"name\":\"name\",\"namespace\":\"crops\",\"type\":\"string\"},{\"name\":\"path\",\"namespace\":\"crops\",\"type\":\"string\"},{\"name\":\"relativePath\",\"namespace\":\"crops\",\"type\":\"string\"},{\"name\":\"width\",\"namespace\":\"crops\",\"type\":\"double\"}],\"name\":\"crops_record\",\"namespace\":\"crops\",\"type\":\"record\"}"
}

func (r *Crops_record) SchemaName() string {
	return "crops.crops_record"
}

func (r *Crops_record) Serialize(w io.Writer) error {
	return writeCrops_record(r, w)
}

func (_ *Crops_record) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ *Crops_record) SetInt(v int32)       { panic("Unsupported operation") }
func (_ *Crops_record) SetLong(v int64)      { panic("Unsupported operation") }
func (_ *Crops_record) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ *Crops_record) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ *Crops_record) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ *Crops_record) SetString(v string)   { panic("Unsupported operation") }
func (_ *Crops_record) SetUnionElem(v int64) { panic("Unsupported operation") }
func (r *Crops_record) Get(i int) types.Field {
	switch i {
	case 0:
		return (*types.Double)(&r.Height)
	case 1:
		return (*types.String)(&r.Name)
	case 2:
		return (*types.String)(&r.Path)
	case 3:
		return (*types.String)(&r.RelativePath)
	case 4:
		return (*types.Double)(&r.Width)

	}
	panic("Unknown field index")
}
func (r *Crops_record) SetDefault(i int) {
	switch i {

	}
	panic("Unknown field index")
}
func (_ *Crops_record) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Crops_record) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *Crops_record) Finalize()                        {}

type Crops_recordReader struct {
	r io.Reader
	p *vm.Program
}

func NewCrops_recordReader(r io.Reader) (*Crops_recordReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewCrops_record()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &Crops_recordReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r *Crops_recordReader) Read() (*Crops_record, error) {
	t := NewCrops_record()
	err := vm.Eval(r.r, r.p, t)
	return t, err
}
