// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.

package complex

import (
	"github.com/actgardner/gogen-avro/compiler"
	"github.com/actgardner/gogen-avro/container"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
	"io"
)

type Meta_record struct {
	Description string
	SiteName    string
}

func NewMeta_recordWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := &Meta_record{}
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

func DeserializeMeta_record(r io.Reader) (*Meta_record, error) {
	t := NewMeta_record()

	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	return t, err
}

func NewMeta_record() *Meta_record {
	return &Meta_record{}
}

func (r *Meta_record) Schema() string {
	return "{\"fields\":[{\"name\":\"description\",\"namespace\":\"URL.meta\",\"type\":\"string\"},{\"name\":\"siteName\",\"namespace\":\"URL.meta\",\"type\":\"string\"}],\"name\":\"meta_record\",\"namespace\":\"URL.meta\",\"type\":\"record\"}"
}

func (r *Meta_record) SchemaName() string {
	return "URL.meta.meta_record"
}

func (r *Meta_record) Serialize(w io.Writer) error {
	return writeMeta_record(r, w)
}

func (_ *Meta_record) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ *Meta_record) SetInt(v int32)       { panic("Unsupported operation") }
func (_ *Meta_record) SetLong(v int64)      { panic("Unsupported operation") }
func (_ *Meta_record) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ *Meta_record) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ *Meta_record) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ *Meta_record) SetString(v string)   { panic("Unsupported operation") }
func (_ *Meta_record) SetUnionElem(v int64) { panic("Unsupported operation") }
func (r *Meta_record) Get(i int) types.Field {
	switch i {
	case 0:
		return (*types.String)(&r.Description)
	case 1:
		return (*types.String)(&r.SiteName)

	}
	panic("Unknown field index")
}
func (r *Meta_record) SetDefault(i int) {
	switch i {

	}
	panic("Unknown field index")
}
func (_ *Meta_record) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Meta_record) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *Meta_record) Finalize()                        {}

type Meta_recordReader struct {
	r io.Reader
	p *vm.Program
}

func NewMeta_recordReader(r io.Reader) (*Meta_recordReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewMeta_record()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &Meta_recordReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r *Meta_recordReader) Read() (*Meta_record, error) {
	t := NewMeta_record()
	err := vm.Eval(r.r, r.p, t)
	return t, err
}
