// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.

package complex

import (
	"fmt"
	"github.com/actgardner/gogen-avro/vm/types"
	"io"
	"math"
)

type ByteWriter interface {
	Grow(int)
	WriteByte(byte) error
}

type StringWriter interface {
	WriteString(string) (int, error)
}

func encodeFloat(w io.Writer, byteCount int, bits uint64) error {
	var err error
	var bb []byte
	bw, ok := w.(ByteWriter)
	if ok {
		bw.Grow(byteCount)
	} else {
		bb = make([]byte, 0, byteCount)
	}
	for i := 0; i < byteCount; i++ {
		if bw != nil {
			err = bw.WriteByte(byte(bits & 255))
			if err != nil {
				return err
			}
		} else {
			bb = append(bb, byte(bits&255))
		}
		bits = bits >> 8
	}
	if bw == nil {
		_, err = w.Write(bb)
		return err
	}
	return nil
}

func encodeInt(w io.Writer, byteCount int, encoded uint64) error {
	var err error
	var bb []byte
	bw, ok := w.(ByteWriter)
	// To avoid reallocations, grow capacity to the largest possible size
	// for this integer
	if ok {
		bw.Grow(byteCount)
	} else {
		bb = make([]byte, 0, byteCount)
	}

	if encoded == 0 {
		if bw != nil {
			err = bw.WriteByte(0)
			if err != nil {
				return err
			}
		} else {
			bb = append(bb, byte(0))
		}
	} else {
		for encoded > 0 {
			b := byte(encoded & 127)
			encoded = encoded >> 7
			if !(encoded == 0) {
				b |= 128
			}
			if bw != nil {
				err = bw.WriteByte(b)
				if err != nil {
					return err
				}
			} else {
				bb = append(bb, b)
			}
		}
	}
	if bw == nil {
		_, err := w.Write(bb)
		return err
	}
	return nil

}

func writeArrayCrops_record(r []*Crops_record, w io.Writer) error {
	err := writeLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeCrops_record(e, w)
		if err != nil {
			return err
		}
	}
	return writeLong(0, w)
}

func writeArrayLong(r []int64, w io.Writer) error {
	err := writeLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeLong(e, w)
		if err != nil {
			return err
		}
	}
	return writeLong(0, w)
}

func writeBool(r bool, w io.Writer) error {
	var b byte
	if r {
		b = byte(1)
	}

	var err error
	if bw, ok := w.(ByteWriter); ok {
		err = bw.WriteByte(b)
	} else {
		bb := make([]byte, 1)
		bb[0] = b
		_, err = w.Write(bb)
	}
	if err != nil {
		return err
	}
	return nil
}

func writeComplex(r *Complex, w io.Writer) error {
	var err error
	err = writeLong(r.AvroWriteTime, w)
	if err != nil {
		return err
	}
	err = writeBool(r.AvroDeleted, w)
	if err != nil {
		return err
	}
	err = writeUnionNullLong(r.Height, w)
	if err != nil {
		return err
	}
	err = writeSomeDateObj_record(r.SomeDateObj, w)
	if err != nil {
		return err
	}
	err = writeBool(r.Visible, w)
	if err != nil {
		return err
	}
	err = writeUnionNullDouble(r.Width, w)
	if err != nil {
		return err
	}
	err = writeString(r.Caption, w)
	if err != nil {
		return err
	}
	err = writeString(r.Credit, w)
	if err != nil {
		return err
	}
	err = writeArrayCrops_record(r.Crops, w)
	if err != nil {
		return err
	}
	err = writeUnionNullString(r.Cutline, w)
	if err != nil {
		return err
	}
	err = writeLong(r.DatePhotoTaken, w)
	if err != nil {
		return err
	}
	err = writeString(r.Orientation, w)
	if err != nil {
		return err
	}
	err = writeOriginalSize_record(r.OriginalSize, w)
	if err != nil {
		return err
	}
	err = writeString(r.Type, w)
	if err != nil {
		return err
	}
	err = writeURL_record(r.URL, w)
	if err != nil {
		return err
	}

	return nil
}
func writeCrops_record(r *Crops_record, w io.Writer) error {
	var err error
	err = writeDouble(r.Height, w)
	if err != nil {
		return err
	}
	err = writeString(r.Name, w)
	if err != nil {
		return err
	}
	err = writeString(r.Path, w)
	if err != nil {
		return err
	}
	err = writeString(r.RelativePath, w)
	if err != nil {
		return err
	}
	err = writeDouble(r.Width, w)
	if err != nil {
		return err
	}

	return nil
}

func writeDouble(r float64, w io.Writer) error {
	bits := uint64(math.Float64bits(r))
	const byteCount = 8
	return encodeFloat(w, byteCount, bits)
}

func writeLong(r int64, w io.Writer) error {
	downShift := uint64(63)
	encoded := uint64((r << 1) ^ (r >> downShift))
	const maxByteSize = 10
	return encodeInt(w, maxByteSize, encoded)
}

func writeMeta_record(r *Meta_record, w io.Writer) error {
	var err error
	err = writeString(r.Description, w)
	if err != nil {
		return err
	}
	err = writeString(r.SiteName, w)
	if err != nil {
		return err
	}

	return nil
}

func writeNull(_ interface{}, _ io.Writer) error {
	return nil
}

func writeOriginalSize_record(r *OriginalSize_record, w io.Writer) error {
	var err error
	err = writeDouble(r.Height, w)
	if err != nil {
		return err
	}
	err = writeDouble(r.Width, w)
	if err != nil {
		return err
	}

	return nil
}
func writeSomeDateObj_record(r *SomeDateObj_record, w io.Writer) error {
	var err error
	err = writeArrayLong(r.Dates, w)
	if err != nil {
		return err
	}

	return nil
}

func writeString(r string, w io.Writer) error {
	err := writeLong(int64(len(r)), w)
	if err != nil {
		return err
	}
	if sw, ok := w.(StringWriter); ok {
		_, err = sw.WriteString(r)
	} else {
		_, err = w.Write([]byte(r))
	}
	return err
}

func writeURL_record(r *URL_record, w io.Writer) error {
	var err error
	err = writeString(r.Absolute, w)
	if err != nil {
		return err
	}
	err = writeMeta_record(r.Meta, w)
	if err != nil {
		return err
	}
	err = writeString(r.Publish, w)
	if err != nil {
		return err
	}

	return nil
}

func writeUnionNullDouble(r *UnionNullDouble, w io.Writer) error {
	err := writeLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullDoubleTypeEnumNull:
		return writeNull(r.Null, w)
	case UnionNullDoubleTypeEnumDouble:
		return writeDouble(r.Double, w)

	}
	return fmt.Errorf("invalid value for *UnionNullDouble")
}

func writeUnionNullLong(r *UnionNullLong, w io.Writer) error {
	err := writeLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullLongTypeEnumNull:
		return writeNull(r.Null, w)
	case UnionNullLongTypeEnumLong:
		return writeLong(r.Long, w)

	}
	return fmt.Errorf("invalid value for *UnionNullLong")
}

func writeUnionNullString(r *UnionNullString, w io.Writer) error {
	err := writeLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullStringTypeEnumNull:
		return writeNull(r.Null, w)
	case UnionNullStringTypeEnumString:
		return writeString(r.String, w)

	}
	return fmt.Errorf("invalid value for *UnionNullString")
}

type ArrayLongWrapper []int64

func (_ *ArrayLongWrapper) SetBoolean(v bool)                { panic("Unsupported operation") }
func (_ *ArrayLongWrapper) SetInt(v int32)                   { panic("Unsupported operation") }
func (_ *ArrayLongWrapper) SetLong(v int64)                  { panic("Unsupported operation") }
func (_ *ArrayLongWrapper) SetFloat(v float32)               { panic("Unsupported operation") }
func (_ *ArrayLongWrapper) SetDouble(v float64)              { panic("Unsupported operation") }
func (_ *ArrayLongWrapper) SetBytes(v []byte)                { panic("Unsupported operation") }
func (_ *ArrayLongWrapper) SetString(v string)               { panic("Unsupported operation") }
func (_ *ArrayLongWrapper) SetUnionElem(v int64)             { panic("Unsupported operation") }
func (_ *ArrayLongWrapper) Get(i int) types.Field            { panic("Unsupported operation") }
func (_ *ArrayLongWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *ArrayLongWrapper) Finalize()                        {}
func (_ *ArrayLongWrapper) SetDefault(i int)                 { panic("Unsupported operation") }
func (r *ArrayLongWrapper) AppendArray() types.Field {
	var v int64

	*r = append(*r, v)
	return (*types.Long)(&(*r)[len(*r)-1])
}

type ArrayCrops_recordWrapper []*Crops_record

func (_ *ArrayCrops_recordWrapper) SetBoolean(v bool)                { panic("Unsupported operation") }
func (_ *ArrayCrops_recordWrapper) SetInt(v int32)                   { panic("Unsupported operation") }
func (_ *ArrayCrops_recordWrapper) SetLong(v int64)                  { panic("Unsupported operation") }
func (_ *ArrayCrops_recordWrapper) SetFloat(v float32)               { panic("Unsupported operation") }
func (_ *ArrayCrops_recordWrapper) SetDouble(v float64)              { panic("Unsupported operation") }
func (_ *ArrayCrops_recordWrapper) SetBytes(v []byte)                { panic("Unsupported operation") }
func (_ *ArrayCrops_recordWrapper) SetString(v string)               { panic("Unsupported operation") }
func (_ *ArrayCrops_recordWrapper) SetUnionElem(v int64)             { panic("Unsupported operation") }
func (_ *ArrayCrops_recordWrapper) Get(i int) types.Field            { panic("Unsupported operation") }
func (_ *ArrayCrops_recordWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *ArrayCrops_recordWrapper) Finalize()                        {}
func (_ *ArrayCrops_recordWrapper) SetDefault(i int)                 { panic("Unsupported operation") }
func (r *ArrayCrops_recordWrapper) AppendArray() types.Field {
	var v *Crops_record
	v = NewCrops_record()

	*r = append(*r, v)
	return (*r)[len(*r)-1]
}
