// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.

package complex

import (
	"github.com/actgardner/gogen-avro/compiler"
	"github.com/actgardner/gogen-avro/container"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
	"io"
)

type SomeDateObj_record struct {
	Dates []int64
}

func NewSomeDateObj_recordWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := &SomeDateObj_record{}
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

func DeserializeSomeDateObj_record(r io.Reader) (*SomeDateObj_record, error) {
	t := NewSomeDateObj_record()

	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	return t, err
}

func NewSomeDateObj_record() *SomeDateObj_record {
	return &SomeDateObj_record{}
}

func (r *SomeDateObj_record) Schema() string {
	return "{\"fields\":[{\"name\":\"dates\",\"namespace\":\"Simple.someDateObj\",\"type\":{\"items\":{\"logicalType\":\"timestamp-millis\",\"type\":\"long\"},\"type\":\"array\"}}],\"name\":\"someDateObj_record\",\"namespace\":\"Simple.someDateObj\",\"type\":\"record\"}"
}

func (r *SomeDateObj_record) SchemaName() string {
	return "Simple.someDateObj.someDateObj_record"
}

func (r *SomeDateObj_record) Serialize(w io.Writer) error {
	return writeSomeDateObj_record(r, w)
}

func (_ *SomeDateObj_record) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ *SomeDateObj_record) SetInt(v int32)       { panic("Unsupported operation") }
func (_ *SomeDateObj_record) SetLong(v int64)      { panic("Unsupported operation") }
func (_ *SomeDateObj_record) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ *SomeDateObj_record) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ *SomeDateObj_record) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ *SomeDateObj_record) SetString(v string)   { panic("Unsupported operation") }
func (_ *SomeDateObj_record) SetUnionElem(v int64) { panic("Unsupported operation") }
func (r *SomeDateObj_record) Get(i int) types.Field {
	switch i {
	case 0:
		r.Dates = make([]int64, 0)
		return (*ArrayLongWrapper)(&r.Dates)

	}
	panic("Unknown field index")
}
func (r *SomeDateObj_record) SetDefault(i int) {
	switch i {

	}
	panic("Unknown field index")
}
func (_ *SomeDateObj_record) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *SomeDateObj_record) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *SomeDateObj_record) Finalize()                        {}

type SomeDateObj_recordReader struct {
	r io.Reader
	p *vm.Program
}

func NewSomeDateObj_recordReader(r io.Reader) (*SomeDateObj_recordReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewSomeDateObj_record()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &SomeDateObj_recordReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r *SomeDateObj_recordReader) Read() (*SomeDateObj_record, error) {
	t := NewSomeDateObj_record()
	err := vm.Eval(r.r, r.p, t)
	return t, err
}
