// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
package complex

import (
	"io"

	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
)

func writeArrayContributors_record(r []*Contributors_record, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeContributors_record(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayContributors_recordWrapper struct {
	Target *[]*Contributors_record
}

func (_ *ArrayContributors_recordWrapper) SetBoolean(v bool)     { panic("Unsupported operation") }
func (_ *ArrayContributors_recordWrapper) SetInt(v int32)        { panic("Unsupported operation") }
func (_ *ArrayContributors_recordWrapper) SetLong(v int64)       { panic("Unsupported operation") }
func (_ *ArrayContributors_recordWrapper) SetFloat(v float32)    { panic("Unsupported operation") }
func (_ *ArrayContributors_recordWrapper) SetDouble(v float64)   { panic("Unsupported operation") }
func (_ *ArrayContributors_recordWrapper) SetBytes(v []byte)     { panic("Unsupported operation") }
func (_ *ArrayContributors_recordWrapper) SetString(v string)    { panic("Unsupported operation") }
func (_ *ArrayContributors_recordWrapper) SetUnionElem(v int64)  { panic("Unsupported operation") }
func (_ *ArrayContributors_recordWrapper) Get(i int) types.Field { panic("Unsupported operation") }
func (_ *ArrayContributors_recordWrapper) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ *ArrayContributors_recordWrapper) Finalize()        {}
func (_ *ArrayContributors_recordWrapper) SetDefault(i int) { panic("Unsupported operation") }
func (r *ArrayContributors_recordWrapper) NullField(i int) {
	panic("Unsupported operation")
}

func (r *ArrayContributors_recordWrapper) AppendArray() types.Field {
	var v *Contributors_record
	v = NewContributors_record()

	*r.Target = append(*r.Target, v)

	return (*r.Target)[len(*r.Target)-1]
}
