name: test

on: [push, pull_request]

jobs:
  golang:
    env:
      WORKFLOW_GO_VERSION: "1.22.3"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version }}
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "~${{ env.WORKFLOW_GO_VERSION }}"
      - name: Build go cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: go vet
        run: go vet ./...
      - name: go test
        run: go test -v -race -parallel 4 -coverprofile=covprofile -covermode=atomic ./...
      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github