name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  golang:
    env:
      GO111MODULE: on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.5'
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-$GITHUB_REPOSITORY-${{ hashFiles('**/go.mod') }}
      - name: deps
        run: go get github.com/mattn/goveralls
      - name: go vet
        run: go vet ./...
      - name: go test race
        run: go test -v -race -parallel 4 -coverprofile=coverage.txt -covermode=atomic ./...
      - name: goveralls
        run: goveralls -coverprofile=coverage.txt -service=travis-ci -ignore=generate/avro_test_data/*,generate/generate_test_data/*,struct_test_data/*