name: test

on: [push, pull_request]

jobs:
  golang:
    env:
      GO111MODULE: on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.5'
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-$GITHUB_REPOSITORY-${{ hashFiles('**/go.mod') }}
      - name: go vet
        run: go vet ./...
      - name: go test race
        run: go test -v -race -parallel 4 -coverprofile=covprofile -covermode=atomic ./...
      - name: install goveralls
        env:
          GO111MODULE: off
        run: go get github.com/mattn/goveralls
      - name: send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github